### ISSUE TITLE
No support for decimal numbers

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-qtype_stack#4]
A question such as asking the students to differentiate 0.123x^2+09.6x+48100 seems to work without the WYSIWYG editor if «forbid float» is turned off. However, using the WYSIWYG editor, the same answer yields «This answer is invalid. Encountered unsupported character: .» in the validation display.

**Comment by andstor** [comment]
Yes, it seems that i have forgotten to support decimals in the [TeX2Max](https://github.com/KQMATH/tex2max) library :sweat_smile:. I have created an issue, see KQMATH/tex2max#44

**Comment by hgeorgsch** [comment]
Nah.  This /is/ a bug rather than an enhancement.  The check box to permit decimal (floating point) numbers is already there, but it does not work with the WYSIWYG editor.

**Comment by andstor** [comment]
I have released TeX2Max v1.3.0 that now supports decimal points.
See KQMATH/tex2max#44.

I have also updated STACK to use TeX2Max v1.3.0. See 85bc5883a3469395877d6048faebd34e0954157d.
